Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,7 @@ jobs:
         name: Get latest version
         run: |
           #!/bin/bash
-          distro="rhel-10-for-x86_64-appstream-rpms"
+          distro="rhel-9-for-x86_64-appstream-rpms"
           resp=$(curl -sS https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token=${{ secrets.REDHAT_TOKEN }})
           token=$(echo "$resp" | jq --raw-output .access_token)
           offset=5000
@@ -31,8 +31,8 @@ jobs:
           do
             echo "Offset $offset"
             resp=$(curl -s -H "Authorization: Bearer $token" -X GET "https://api.access.redhat.com/management/v1/packages/cset/$distro/arch/x86_64?limit=$limit&offset=$offset&filter=latest" -H "accept: application/json")
-            echo "$resp" | grep -q 'count":0}' && exit 34
-            echo "$resp" | grep -q '{"error":{"code":' && exit 35
+            echo "$resp" | grep -q 'count":0}' && echo "$resp" && exit 34
+            echo "$resp" | grep -q '{"error":{"code":' && echo "$resp" && exit 35
             echo "$resp"
             offset=$((offset+limit))
             sleep 0.2
